image: node:latest

stages:
  - linting-frontend
  - test-backend
  - build
  - push
  # - build-backend

lint-test-job:
  stage: linting-frontend
  script:
    - cd frontend/
    - echo "Linting..."
    - npm run lint

unit-test-backend-authservice-job:
  image: python
  stage: test-backend
  script:
    - cd backend/AuthenticateService/
    - pip3 install -r requirements.txt
    - python3 unit_test.py

build-job:
  stage: build
  script:
    - docker-compose up --build

push-job:
  stage: push
  script:
    - docker image tag mumble/vue-frontend-app:latest scarydemondocker/mumble:latest
    - docker image push scarydemondocker/mumble:latest

# build-job-backend:
#   image: python
#   stage: build-backend
#   script:
#     - cd backend/AuthenticateService/
#     - pip3 install -r requirements.txt
#     - python3 main.py
  

# build-job-APIgateway:
#   image: python
#   stage: build-backend
#   script:
#     - cd backend/API-gateway/
#     - python3 main.py

