image: node:latest

cache:
  paths:
    - frontend/node_modules/

stages:
  - setup-frontend
  - build-frontend
  - linting-frontend
  - test-backend
  # - build-backend

setup_npm:
  stage: setup-frontend
  script:
    - cd frontend/
    - echo "installing..."
    - npm install

build-job-frontend:
  stage: build-frontend
  script:
    - cd frontend/
    - echo "building..."
    - npm run build

lint-test-job:
  stage: linting-frontend
  script:
    - cd frontend/
    - echo "Linting..."
    - npm run lint

unit-test-backend-authservice-job:
  image: python
  stage: test-backend
  script:
    - cd backend/AuthenticateService/
    - pip3 install -r requirements.txt
    - python3 unit_test.py

# build-job-backend:
#   image: python
#   stage: build-backend
#   script:
#     - cd backend/AuthenticateService/
#     - pip3 install -r requirements.txt
#     - python3 main.py
  

# build-job-APIgateway:
#   image: python
#   stage: build-backend
#   script:
#     - cd backend/API-gateway/
#     - python3 main.py

